# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/ha3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
  vendor/samsung/ha3g/proprietary/lib/hw/audio.primary.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.vendor.universal5420.so \
  vendor/samsung/ha3g/proprietary/lib/libymc_codecctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libymc_codecctrl.so \
  vendor/samsung/ha3g/proprietary/lib/libymc_config.so:$(TARGET_COPY_OUT_VENDOR)/lib/libymc_config.so \
  vendor/samsung/ha3g/proprietary/lib/libsamsungSoundbooster_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungSoundbooster_ext.so \
  vendor/samsung/ha3g/proprietary/lib/lib_Samsung_Resampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_Resampler.so \
  vendor/samsung/ha3g/proprietary/lib/lib_soundaliveresampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_soundaliveresampler.so \
  vendor/samsung/ha3g/proprietary/lib/libsamsungRecord.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord.so \
  vendor/samsung/ha3g/proprietary/lib/libsamsungRecord_ns.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord_ns.so \
  vendor/samsung/ha3g/proprietary/lib/libsamsungRecord_zoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord_zoom.so \
  vendor/samsung/ha3g/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundAlive_SRC192_ver205.so \
  vendor/samsung/ha3g/proprietary/lib/lib_SamsungRec_V04004.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SamsungRec_V04004.so \
  vendor/samsung/ha3g/proprietary/lib/lib_DNSe_NRSS_ver226.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_DNSe_NRSS_ver226.so \
  vendor/samsung/ha3g/proprietary/lib/lib_Samsung_AudioZoom_v102.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_AudioZoom_v102.so \
  vendor/samsung/ha3g/proprietary/lib/lib_SoundBooster_ver402.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundBooster_ver402.so \
  vendor/samsung/ha3g/proprietary/lib/libmysound.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmysound.so \
  vendor/samsung/ha3g/proprietary/lib/libaudiosa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiosa.so \
  vendor/samsung/ha3g/proprietary/lib/lib_SA_GoogleFX_ver124b.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SA_GoogleFX_ver124b.so \
  vendor/samsung/ha3g/proprietary/lib/soundfx/libaudiosa_sec.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libaudiosa_sec.so \
  vendor/samsung/ha3g/proprietary/lib/lib_SoundAlive_play_ver125e.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundAlive_play_ver125e.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/liblvverx_3.20.03.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblvverx_3.20.03.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/liblvvetx_3.20.03.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblvvetx_3.20.03.so \
  vendor/samsung/ha3g/proprietary/usr/share/alsa/alsa.conf:$(TARGET_COPY_OUT_SYSTEM)/usr/share/alsa/alsa.conf \
  vendor/samsung/ha3g/proprietary/vendor/firmware/srp_cga.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/srp_cga.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/srp_data.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/srp_data.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/srp_vliw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/srp_vliw.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/bcm4335_V0091.0405_wisol.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4335_V0091.0405_wisol.hcd \
  vendor/samsung/ha3g/proprietary/vendor/firmware/bcm4335_V0093.0400.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4335_V0093.0400.hcd \
  vendor/samsung/ha3g/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
  vendor/samsung/ha3g/proprietary/lib/hw/camera.vendor.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.vendor.universal5420.so \
  vendor/samsung/ha3g/proprietary/lib/libexynoscamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynoscamera.so \
  vendor/samsung/ha3g/proprietary/lib/libarcsoft_nighthawk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_nighthawk.so \
  vendor/samsung/ha3g/proprietary/lib/libliveframework.so:$(TARGET_COPY_OUT_VENDOR)/lib/libliveframework.so \
  vendor/samsung/ha3g/proprietary/lib/libvdis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvdis.so \
  vendor/samsung/ha3g/proprietary/bin/drmserver.samsung:$(TARGET_COPY_OUT_VENDOR)/bin/drmserver.samsung \
  vendor/samsung/ha3g/proprietary/lib/libdrmdecrypt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdecrypt.so \
  vendor/samsung/ha3g/proprietary/lib/libstagefright_hdcp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_hdcp.so \
  vendor/samsung/ha3g/proprietary/lib/libhdcp2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhdcp2.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libwvdrm_L1.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libWVStreamControlAPI_L1.so \
  vendor/samsung/ha3g/proprietary/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/libwvm.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/vendor/lib/mediadrm/libwvdrmengine.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
  vendor/samsung/ha3g/proprietary/vendor/lib/libmalicore.bc:$(TARGET_COPY_OUT_VENDOR)/lib/libmalicore.bc \
  vendor/samsung/ha3g/proprietary/vendor/lib/libRSDriverArm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriverArm.so \
  vendor/samsung/ha3g/proprietary/bin/gpsd:$(TARGET_COPY_OUT_VENDOR)/bin/hw/gpsd \
  vendor/samsung/ha3g/proprietary/lib/hw/gps.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.default.so \
  vendor/samsung/ha3g/proprietary/lib/libwrappergps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwrappergps.so \
  vendor/samsung/ha3g/proprietary/vendor/firmware/fimc_is_fw2_3L2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2_3L2.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/fimc_is_fw2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/setfile_3L2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3L2.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/setfile_6b2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_6b2.bin \
  vendor/samsung/ha3g/proprietary/vendor/firmware/setfile_imx135.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx135.bin \
  vendor/samsung/ha3g/proprietary/app/FFFFFFFF000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/FFFFFFFF000000000000000000000001.drbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/00060308060501020000000000000000.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/02010000080300030000000000000000.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000000000.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000003.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000003.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000007.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000007.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000008.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000008.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000009.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000010.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000010.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000011.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000011.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffff000000000000000000000018.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
  vendor/samsung/ha3g/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
  vendor/samsung/ha3g/proprietary/bin/scranton_RD:$(TARGET_COPY_OUT_VENDOR)/bin/scranton_RD \
  vendor/samsung/ha3g/proprietary/bin/sensorhubservice:$(TARGET_COPY_OUT_VENDOR)/bin/sensorhubservice \
  vendor/samsung/ha3g/proprietary/lib/hw/sensorhubs.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensorhubs.universal5420.so \
  vendor/samsung/ha3g/proprietary/lib/libgnustl_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgnustl_shared.so \
  vendor/samsung/ha3g/proprietary/lib/hw/sensors.universal5420.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.vendor.universal5420.so \
  vendor/samsung/ha3g/proprietary/lib/libsensirion_h_3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensirion_h_3.so \
  vendor/samsung/ha3g/proprietary/lib/libsensorhub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorhub.so \
  vendor/samsung/ha3g/proprietary/lib/libsensorhubservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorhubservice.so \
  vendor/samsung/ha3g/proprietary/vendor/firmware/bcm2079xB4_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm2079xB4_firmware.ncd \
  vendor/samsung/ha3g/proprietary/vendor/firmware/bcm2079xB4_pre_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm2079xB4_pre_firmware.ncd \
  vendor/samsung/ha3g/proprietary/vendor/firmware/bcm2079xB5_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm2079xB5_firmware.ncd \
  vendor/samsung/ha3g/proprietary/vendor/firmware/bcm2079xB5_pre_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm2079xB5_pre_firmware.ncd \
  vendor/samsung/ha3g/proprietary/lib/libaudio-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio-ril.so \
  vendor/samsung/ha3g/proprietary/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
  vendor/samsung/ha3g/proprietary/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_apsta.bin \
  vendor/samsung/ha3g/proprietary/etc/wifi/bcmdhd_ibss.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_ibss.bin \
  vendor/samsung/ha3g/proprietary/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_mfg.bin \
  vendor/samsung/ha3g/proprietary/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_sta.bin \
  vendor/samsung/ha3g/proprietary/etc/wifi/cred.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/cred.conf \
  vendor/samsung/ha3g/proprietary/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt \
  vendor/samsung/ha3g/proprietary/etc/wifi/nvram_mfg.txt_semco3rd:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_semco3rd \
  vendor/samsung/ha3g/proprietary/etc/wifi/nvram_mfg.txt_wisol:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_wisol \
  vendor/samsung/ha3g/proprietary/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt \
  vendor/samsung/ha3g/proprietary/etc/wifi/nvram_net.txt_semco3rd:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_semco3rd \
  vendor/samsung/ha3g/proprietary/etc/wifi/nvram_net.txt_wisol:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_wisol
